services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend-test:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: build
    command: mvn clean test -pl backend -am
    depends_on:
      - backend

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    command: npm run test
    depends_on:
      - backend